config/routes.rb
ResumeViewer::Application.routes.draw do

  get "sessions/new"

  get "home/index_temp"

  resources :users do
     resources :resumes do
        resources :sections do
          resources :items
        end
     end
  end

  resources :recruiters
  
  resources :companies do
    resources :positions
  end

  resources :sessions
  
  resources :employments
  resources :applications

  root :to => 'home#index_temp'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recruiter_log_in" => "sessions#new_recruiter", :as => "recruiter_log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "recruiter_sign_up" => "recruiters#new", :as => "recruiter_sign_up"

  get "test_site" => 'home#index', :as => "test_site"
  
  match 'uploads' => 'resumes#upload', :as => 'resume_upload'

  match "/recruiters/approve/:employment_id" => "recruiters#approve", :as =>"recruiter_approve_employment", :via => :put

end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :company
  has_many :applications
  has_many :resumes, :through => :applications
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authorize, :only => [:edit, :update, :new, :create]
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :ok }
    end
  end
  
    private

  def authorize
    @company = Company.find(params[:company_id])
    unless user_session.recruiter_works_for_company?(@company)
      @position = Position.find(params[:id])
      flash[:notice] = "You must work for this company to view that page."
      redirect_to [@company, @position]
    end
  end
  
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :numPositions %><br />
    <%= f.text_field :numPositions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Edit Position Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>Category</th>
    <th>Description</th>
    <th>Numpositions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.title %></td>
    <td><%= position.company %></td>
    <td><%= position.category %></td>
    <td><%= position.description %></td>
    <td><%= position.numPositions %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>Create a New Position Profile</h1>

<%= render 'form' %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @position.title %>
</p>

<p>
  <b>Company:</b>
  <%= @position.company %>
</p>

<p>
  <b>Category:</b>
  <%= @position.category %>
</p>

<p>
  <b>Description:</b>
  <%= @position.description %>
</p>

<p>
  <b>Numpositions:</b>
  <%= @position.numPositions %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>