config/routes.rb
ResumeViewer::Application.routes.draw do

  get "sessions/new"

  get "home/index_temp"

  resources :users do
     resources :resumes do
        resources :sections do
          resources :items
        end
     end
  end

  resources :recruiters
  
  resources :companies do
    resources :positions
  end

  resources :sessions
  
  resources :employments
  resources :applications

  root :to => 'home#index_temp'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recruiter_log_in" => "sessions#new_recruiter", :as => "recruiter_log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "recruiter_sign_up" => "recruiters#new", :as => "recruiter_sign_up"

  get "test_site" => 'home#index', :as => "test_site"
  
  match 'uploads' => 'resumes#upload', :as => 'resume_upload'

  match "/recruiters/approve/:employment_id" => "recruiters#approve", :as =>"recruiter_approve_employment", :via => :put

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :position
  belongs_to :resume
end

app/models/company.rb
class Company < ActiveRecord::Base
   validates_presence_of :name
   validates_uniqueness_of :name
  belongs_to :recruiter
  has_many :employments
  has_many :recruiters, :through => :employments 
    def newRecruiter(recruiter_id, requestType)
        empl = Employment.new(:recruiter_id => recruiter_id, :company_id => self.id, :requestType => requestType)
        empl.save
    end
    
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :company
  belongs_to :recruiter
   
    def approvedByBoth()
      self.requestType=1
      return self.save
    end

end

# rails generate model employment company_id:integer recruiter_id:integer created_at:datetime

app/models/item.rb
class Item < ActiveRecord::Base
   validates :positiontitle, :presence => true
   validates :order, :presence => true

  belongs_to :section

end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :company
  has_many :applications
  has_many :resumes, :through => :applications
end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
  
   has_many :employments
   has_many :companies, :through => :employments 
    def push_with_attributes(company, join_attrs)
      Employments.with_scope(:create => join_attrs) { self << company}
    end
  
   attr_accessible :username, :email, :password, :password_confirmation, :company

   attr_accessor :password
   before_save :encrypt_password

   validates_confirmation_of :password, :message => 'and Password confirmation do not match'
   validates_presence_of :password, :on => :create
   validates_presence_of :username
   validates_presence_of :email
   validates_uniqueness_of :email
   validates_format_of :email,
                      :with => /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}/i,
                      :message => "must be a valid address"
   validates_uniqueness_of :username

   def self.authenticate(username, password)
      user = find_by_username(username)
      if user && user.passwordHash == BCrypt::Engine.hash_secret(password, user.passwordSalt)
         user
      else
         nil
      end
   end
   
   def encrypt_password
      if password.present?
         self.passwordSalt = BCrypt::Engine.generate_salt
         self.passwordHash = BCrypt::Engine.hash_secret(password, passwordSalt)
      end
   end
  
end

app/models/resume.rb
class Resume < ActiveRecord::Base
   validates :resumeName, :presence => true

   belongs_to :user

   has_many :sections
   
   
  has_many :applications
  has_many :resumes, :through => :applications
  
    def processResumeLines(lines)
      return lines.join("***")
    end

end

app/models/resume_item.rb
class ResumeItem < ActiveRecord::Base

  belongs_to :resume

end

app/models/section.rb
class Section < ActiveRecord::Base
   belongs_to :resume
   validates :order, :presence => true

   has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base

   attr_accessible :username, :email, :password, :password_confirmation

   attr_accessor :password
   before_save :encrypt_password

   validates_confirmation_of :password, :message => 'and Password confirmation do not match'
   validates_presence_of :password, :on => :create
   validates_presence_of :username
   validates_presence_of :email
   validates_uniqueness_of :email
   validates_format_of :email,
                      :with => /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}/i,
                      :message => "must be a valid address"
   validates_uniqueness_of :username

   def self.authenticate(username, password)
      user = find_by_username(username)
      if user && user.passwordHash == BCrypt::Engine.hash_secret(password, user.passwordSalt)
         user
      else
         nil
      end
   end
   
   def encrypt_password
      if password.present?
         self.passwordSalt = BCrypt::Engine.generate_salt
         self.passwordHash = BCrypt::Engine.hash_secret(password, passwordSalt)
      end
   end

   has_many :resumes
end

app/models/user_session.rb
class UserSession
  def initialize(session)
    @session = session
    @user_id ||= @session[:user_id]
  end
  
  def setAsRecruiter()
    @session[:rec] = true
  end
  
  def isRecruiter()
    return @session[:rec]
  end
  
  def loginUser(user_id)
    @session[:user_id] = user_id
  end
  
  def loginRecruiter(recruiter_id)
    @session[:recruiter_id] = recruiter_id
  end
  
  def right_user?(user_id)
    @session[:user_id] && @session[:user_id]==user_id
  end
  
  def right_recruiter?(recruiter_id)
    @session[:recruiter_id] && @session[:recruiter_id]==recruiter_id
  end
  
  def recruiter_is_company_admin?(company)
    @session[:recruiter_id] && @session[:recruiter_id]==company.recruiter.id
  end
  
  def recruiter_works_for_company?(company)
    @session[:recruiter_id] && company.recruiters.include?(@session[:recruiter_id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @user = User.new
    respond_to do |format|
       format.html
       format.json { render :json => @user }
    end
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authorize, :only => [:edit, :update, :new, :create]

   def create
      @user = User.find(params[:user_id])
      @resume = Resume.find(params[:resume_id])
      @section = Section.find(params[:section_id])
      @item = @section.items.create(params[:item])
      redirect_to user_resume_path(@user, @resume)
   end


  def new
    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:resume_id])
    @section = Section.find(params[:section_id])
    @item = Item.new


    respond_to do |format|

      format.html # new.html.erb

      format.json { render :json => @item }

    end

  end


  def update

    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:resume_id])
    @section = Section.find(params[:section_id])
    @item = Item.find(params[:id])

    respond_to do |format|

      if @item.update_attributes(params[:item])

        format.html { redirect_to [@user,@resume], :notice => 'Item was successfully updated.' }

        format.json { head :ok }

      else

        format.html { render :action => "edit" }

        format.json { render :json => @item.errors, :status => :unprocessable_entity }

      end

    end

  end

  def edit
    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:resume_id])
    @section = Section.find(params[:section_id])
    @item = Item.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:resume_id])
    @section = Section.find(params[:section_id])
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_resume_path(@user,@resume)
  end

private

  def authorize
    unless user_session.right_user?(params[:user_id].to_i)
      @user = User.find(params[:user_id])
      @resume = Resume.find(params[:resume_id])
      flash[:notice] = "That's not your resume!"
      redirect_to user_resume_path(@user,@resume)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/resume_items_helper.rb
module ResumeItemsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="home_box">
	
<div class="left">
<%= link_to 'Create a recruiter account', recruiter_sign_up_path %>
<br>
<%= link_to 'Sign in to your recruiter account', recruiter_log_in_path 
%>
<br>
<%= link_to 'List of Users...For Development Purposes', users_path %>
	
</div>

<div class="right">
<%= render 'sessions/login' %>
</div>

<div class="right" id="verticalLine">
<%= (image_tag 'verticalLine.png', :width => "1px", :height => "200px") %>
</div>	

<div class="right">
<%= render 'users/form' %>
</div>


</div>

app/views/home/index2.html.erb
<script type="text/javascript">
document.getElementById("user_nav").innerHTML=""
</script>

<center>
<h1>OneDoss</h1>
<div id="outermostWrapper">
<div id="outerWrapper">
<div id="top">&nbsp</div>
<div id="innerWrapper">
<p>
Coming soon.  A site that lets you showcase your accomplishments alongside your resume.
</p>
</div>
<div id="bottom">&nbsp</div>
</div>
</div>
</center>

app/views/home/index_temp.html.erb
<script type="text/javascript">
removeDiv("headerWrapper");
</script>

<style type="text/css">
body{
	overflow:hidden;
	width:100%;
	padding:0px;
	margin:0px;
	border:0px;
	background: transparent url(/assets/gradient.png) repeat-x;
	text-align:center;
}
</style>

<div id="0" style="font-size:28px;font-family: 'Trebuchet MS','Arial', sans-serif;background-color:#ffffff;padding:50px;padding-top:150px;">
<b>One<font color="#4e7692">Doss</font><font color="#686868">ier</font></b>
<p style="font-size:13px;color:#686868 ;"><b>www.OneDoss.com</b></p>
</div>
<div><img src="/assets/line.png" width="100%" height="16px"></div>
<div id="2" style="padding:50px;">
<p style="font-size:15px;color:#686868 ;"><b><i></i></b></p>
<p style="font-family: 'Trebuchet MS','Arial', sans-serif;font-size:12px;margin-top:-10px;color:#4e7692;"><b>We're coming soon.</b></p>
</div>

app/views/items/_form.html.erb
<%= form_for([@user, @resume, @section, @item]) do |f| %>

  <% if @item.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this resume item from being saved:</h2>


      <ul>

      <% @item.errors.full_messages.each do |msg| %>

        <li><%= msg %></li>

      <% end %>

      </ul>

    </div>

  <% end %>


  
  	
  <div class="left">

    <%= f.label :position_title %><br />

    <%= f.text_field :positiontitle %>

  </div>
  <div class="left">

    <%= f.label :organization %><br />

    <%= f.text_field :organization %>

  </div>
  <div class="left">

    <%= f.label :location %><br />

    <%= f.text_field :location %>

  </div>
  
  <div class="clear"></div>
  
  <div class="left">

    <%= f.label :start_month %><br />

    <%= f.text_field :startMonth %>

  </div>
  <div class="left">

    <%= f.label :start_season %><br />

    <%= f.text_field :startSeason %>

  </div>
  <div class="left">

    <%= f.label :start_year %><br />

    <%= f.text_field :startYear %>

  </div>
  
  <div class="clear"></div>
  
  <div class="left">
    <%= f.check_box :present %>
    I work here now.

  </div>
	
  <div class="clear"></div>
  
  <div id="endDates">
  	
  <div class="left">

    <%= f.label :end_month %><br />

    <%= f.text_field :endMonth %>

  </div>
  <div class="left">

    <%= f.label :end_season %><br />

    <%= f.text_field :endSeason %>

  </div>
  <div class="left">

    <%= f.label :end_year %><br />

    <%= f.text_field :endYear %>

  </div>
  </div>
  
  <div class="clear"></div>
  
  <div class="left">

    <%= f.label :description %><br />

    <%= f.text_area(:description, :cols=>80, :rows=>12) %>

  </div>
  
  <div class="clear"></div>
  
  <div class="left">

    <%= f.label :order %><br />

    <%= f.number_field :order %>

  </div>
  
  <div class="clear"></div>
  
  <div class="left">

    <%= f.label :link %><br />

    <%= f.text_field :link %>

  </div>
  
  <div class="clear"></div>
  
  <div class="actions">

    <%= f.submit %>

  </div>

<% end %>

		<script type="text/javascript">
		//showHideText("item_present", "endDates");
		//document.getElementById("item_present").onclick = showHideText("item_present", "endDates");
		
		document.getElementById("item_present").onclick = function(){;showHideText("item_present", "endDates");};
		showHideText("item_present", "endDates");
		</script>

app/views/items/edit.html.erb
<h1>Edit Resume Item</h1>

<%= render 'form' %>

<%= link_to 'Show Changes', user_resume_path(@user,@resume) %>

app/views/items/new.html.erb
<h1>Add a New Resume Item</h1>


<%= render 'form' %>

app/views/resume_items/_form.html.erb
<%= form_for([@user, @resume, @resume.resume_items.build]) do |f| %>

  <% if @resumeItem.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(@resume_item.errors.count, "error") %> prohibited this resume item from being saved:</h2>


      <ul>

      <% @resumeItem.errors.full_messages.each do |msg| %>

        <li><%= msg %></li>

      <% end %>

      </ul>

    </div>

  <% end %>

  <table>
  <tr>
  <td>
  <div class="field">

    <%= f.label :type %><br />

    <%= f.text_field :type %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :section %><br />

    <%= f.text_field :section %>
  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">

    <%= f.label :position_title %><br />

    <%= f.text_field :positiontitle %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :location %><br />

    <%= f.text_field :location %>

  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">

    <%= f.label :start_month %><br />

    <%= f.text_field :startMonth %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :start_season %><br />

    <%= f.text_field :startSeason %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :start_year %><br />

    <%= f.text_field :startYear %>

  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">

    <%= f.label :end_month %><br />

    <%= f.text_field :endMonth %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :end_season %><br />

    <%= f.text_field :endSeason %>

  </div>
  </td>
  <td>
  <div class="field">

    <%= f.label :end_year %><br />

    <%= f.text_field :endYear %>

  </div>
  </td>
  </tr>
  <tr>
  <td colspan="3">
  <div class="field">

    <%= f.label :description %><br />

    <%= f.text_area(:description, :cols=>80, :rows=>12) %>

  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">

    <%= f.label :order %><br />

    <%= f.number_field :order %>

  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">

    <%= f.label :link %><br />

    <%= f.url_field :link %>

  </div>
  </td>
  </tr>
  </table>
  <div class="actions">

    <%= f.submit %>

  </div>

<% end %>