config/routes.rb
ResumeViewer::Application.routes.draw do

  get "sessions/new"

  get "home/index_temp"

  resources :users do
     resources :resumes do
        resources :sections do
          resources :items
        end
     end
  end

  resources :recruiters
  
  resources :companies do
    resources :positions
  end

  resources :sessions
  
  resources :employments
  resources :applications

  root :to => 'home#index_temp'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recruiter_log_in" => "sessions#new_recruiter", :as => "recruiter_log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "recruiter_sign_up" => "recruiters#new", :as => "recruiter_sign_up"

  get "test_site" => 'home#index', :as => "test_site"
  
  match 'uploads' => 'resumes#upload', :as => 'resume_upload'

  match "/recruiters/approve/:employment_id" => "recruiters#approve", :as =>"recruiter_approve_employment", :via => :put

end

app/models/resume.rb
class Resume < ActiveRecord::Base
   validates :resumeName, :presence => true

   belongs_to :user

   has_many :sections
   
   
  has_many :applications
  has_many :resumes, :through => :applications
  
    def processResumeLines(lines)
      return lines.join("***")
    end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  require 'hpricot'
  require 'zip/zip'
  before_filter :authorize, :only => [:edit, :update, :new, :create]

   def create
      @user = User.find(params[:user_id])
      @resume = @user.resumes.create(params[:resume])
      redirect_to user_resume_path(@user, @resume)
   end


   def show

    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:id])


    respond_to do |format|

      format.html # show.html.erb

      format.json { render :json => @resume }

    end

   end
   
   
   
  def update

    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:id])

    respond_to do |format|

      if @resume.update_attributes(params[:resume])

        format.html { redirect_to [@user,@resume], :notice => 'Item was successfully updated.' }

        format.json { head :ok }

      else

        format.html { render :action => "edit" }

        format.json { render :json => @resume.errors, :status => :unprocessable_entity }

      end

    end

  end

  def edit

    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to user_path(@user)
  end
  
  def upload
    @user = User.find(params[:user_id])
    @resume = @user.resumes.create()
      
    @file = params[:resume]
    zip = Zip::ZipFile.open(@file.tempfile)
    @xml = zip.read("word/document.xml")
   
    doc = Hpricot::XML(@xml)
    @posts = []
    doc.search("w:t|w:b/").each do |p|
      @posts << p.inner_html
    end
    
    @posts2 = []
    doc.search("*").each do |p|
      if p.name=="w:t"
        @posts2 << p.inner_html
      elsif p.name=="w:p"
        @posts2 << "<br>"
      end
    end
    
    inResInfo=true
    inContactInfo=false
    breakCount=0
    currLines=[]
    @results=[]
    
    doc.search("*").each do |p|
      if p.name=="w:t"
        breakCount=0
        # handle adding name to the information stored with the resume object
        if inResInfo
          nameArray=p.inner_html.split(" ")
          if nameArray.length==1
            @resume.lastName=nameArray[0]
          elsif nameArray.length==2
            @resume.firstName=nameArray[0]
            @resume.lastName=nameArray[1]
          elsif nameArray.length>2
            nameLen=nameArray.length
            @resume.firstName=nameArray[0]
            @resume.lastName=nameArray[nameLen-1]
            @resume.middleName=(nameArray[1,nameLen-2]).join(" ")
          end
          inResInfo=false
          inContactInfo=true
        else
          currLines << p.inner_html
        end
      elsif p.name=="w:p"
        breakCount+=1
        if breakCount==2
          if inContactInfo
            newSection = Section.new
            inContactInfo=false
          else
            @results << @resume.processResumeLines(currLines)
            currLines=[]
          end
        end
      end
    end
    
    @results << @resume.processResumeLines(currLines)
    
    respond_to do |format|
      format.html # show.html.erb
    end
    
  end

  private

  def authorize
    unless user_session.right_user?(params[:user_id].to_i)
      @user = User.find(params[:user_id])
      @resume = Resume.find(params[:id])
      flash[:notice] = "That's not your resume!"
      redirect_to user_resume_path(@user,@resume)
    end
  end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/ _referral.html.erb
<%= form_for([@user, @resume]) do |f| %>

  Make a Referral
  
  Send this resume to a recruiter.
  <form action="mailto:admin@example.com" enctype="text/plain" method="post">
	Your Name: <input type="text" name="name"><br>
	Your Email: <input type="text" name="email"><br>
	Comments: <textarea rows="5" cols="30" name="comments"></textarea>
	<input type="submit" value="Send">
  </form>

<% end %>

app/views/resumes/_form.html.erb
<%= form_for([@user, @resume]) do |f| %>

  <div class="left">

    <%= f.label :first_name %><br />

    <%= f.text_field :firstName %>

  </div>
  <div class="left">

    <%= f.label :middle_names %><br />

    <%= f.text_field :middleNames %>

  </div>
  <div class="left">

    <%= f.label :last_name %><br />

    <%= f.text_field :lastName %>

  </div>
  
  <div class="clear"></div>
  
  <div class="left">

    <%= f.label :email %><br />

    <%= f.text_field :email %>
    
  </div>
  
  <div class="left">

    <%= f.label :personal_or_professional_website %><br />

    <%= f.text_field :website %>
    
  </div>

  <div class="clear"></div>

<div class="left">

    <%= f.label :street_address %><br />

    <%= f.text_field :street %>

  </div>
  <div class="left">

    <%= f.label :city %><br />

    <%= f.text_field :city %>

  </div>
  <div class="left">

    <%= f.label :state %><br />

    <%= f.text_field :state %>

  </div>
  <div class="left">

    <%= f.label :country %><br />

    <%= f.text_field :country %>

  </div>
  
  <div class="clear"></div>


  <div class="actions">

    <%= f.submit %>

  </div>

<% end %>

app/views/resumes/edit.html.erb
<h1>Edit Resume Information</h1>

<%= render 'form' %>

app/views/resumes/show.html.erb
<% editable = user_session.right_user?(@user.id) %>

<div id="outermostWrapper">


<div id="resume_portal" class="sortable_section">
	<div id="resume_name">
	<%= @resume.firstName%>
	<%= @resume.middleNames%>
	<%= @resume.lastName%>
	</div>
	<div id="resume_address">
		<%= 
		returnString=""
		if !(@resume.street=="") and !(@resume.street==nil)
			returnString<<@resume.street
		end
		if !(@resume.city=="") and !(@resume.city==nil)
			if !(returnString=="")
				returnString<<(", ")
			end
			returnString<<@resume.city
		end
		if !(@resume.state=="") and !(@resume.state==nil)
			if !(returnString=="")
				returnString<<(", ")
			end
			returnString<<@resume.state
		end
		returnString
		%>
	</div>
	<div id="resume_website">
		<%= if !(@resume.website=="")
			 link_to @resume.website, @resume.website, :target => "_blank"
			 end%>
	</div>
	<div class="clear"></div>
	
	<% if editable%>  
	<%= link_to 'Edit Personal Data Associated with this Resume', edit_user_resume_path(@user, @resume) %>
	<% end %>
	
<% @resume.sections.sort_by {|obj| obj.order}.each do |section| %>
<div class="resume_section">
<h3 class="section_name"><%= image_tag 'moveicon.png', {:height => 10, :class => 'handle_section' } %><span class="edit"><%= section.name %></span></h3>
<div class="section_body sortable_item">
<% section.items.sort_by {|obj| obj.order}.each do |resumeItem| %>
	<div class="section_item">
		<% hasStart = !(resumeItem.startMonth=="") || !(resumeItem.startSeason=="") || !(resumeItem.startYear==nil)%>
       <% hasEnd = !(resumeItem.endMonth=="") || !(resumeItem.endSeason=="") || !(resumeItem.endYear==nil) || (resumeItem.present==true)%>

	  <div class="resume_dates">
		   <%=
		   if resumeItem.startMonth==""
		   	resumeItem.startSeason
		   else
		   	resumeItem.startMonth
		   end
		   %> 
		   <%= resumeItem.startYear %>
		   
		   <% if hasStart && hasEnd %>
		   	-
		   <% end %>
		   
		   <%=
		   if resumeItem.endMonth==""
		   	resumeItem.endSeason
		   else
		   	resumeItem.endMonth
		   end
		   %> 
		   <%= resumeItem.endYear %>
		   <% if (resumeItem.present==true)%>
		   		Present
		   <% end %>
		   
		   <% if hasStart || hasEnd %>
		   	<br>
		   <% end %>
		   
	  </div>
	  <div class="handle_item"><%= image_tag 'arrowmoveicon.png', {:height => 10, :class => 'handle_item' } %></div>
       <span class="bold edit"><%= resumeItem.positiontitle %> </span>
       
       	<br>
	  
	<% if !(resumeItem.link=="")%>
	    <% divName = section.order.to_s+"_"+resumeItem.order.to_s %>
		<div id="<%= divName %>" class="linkArrow">  <%= image_tag 'arrow.png', {:height => 45} %>  </div>
		<script type="text/javascript">
		document.getElementById("<%= divName %>").onmouseover = loadLink("<%= resumeItem.link %>", "<%= divName %>");
		</script>
	<% end %>
	
	  

       <% if (!(resumeItem.organization=="")) &&  (!(resumeItem.location==""))%>
       			<%= resumeItem.organization%>, <i><%= resumeItem.location %></i><br>
       <% elsif !(resumeItem.organization=="")%>
       			<%= resumeItem.organization %><br>
       <% elsif !(resumeItem.location=="")%>
       			<%= resumeItem.location %><br>
       <% end %>
       
       
		   
		   <% if !(resumeItem.description=="")%>
		   		<span class="edit_area"><%= resumeItem.description %></span><br>
		   <% end %>
  
<% if editable%>      
<%= link_to 'Edit', edit_user_resume_section_item_path(@user, @resume, section, resumeItem) %>
<br>  
<%= link_to 'Delete', [@user, @resume, section, resumeItem], :confirm => 'Are you sure you want to delete this item?' , :method => :delete %>
<% end %>

</div>
<% end %>


<% if editable%>  
<%= link_to "Add a New #{section.name} Item", new_user_resume_section_item_path(@user,@resume, section) %>
<% end %>
</div>
</div>
<% end %>


<% if editable%>  
<%= link_to 'Add a New Resume Section', new_user_resume_section_path(@user,@resume) %>
<% end %>
</div>

<div id="linkArrowFrame"></div>

<div id="linkFrameWrapper">
<div id="linkFrame"></div>
</div>

<div class="clear"></div>

<div id="navigation">
<%= link_to 'Back to Resume List', user_path(@user) %>
</div>


</div>

app/views/resumes/upload.html.erb
<% @posts.each do |post| %>
	<%= post%>
	<br>
<% end %>

<br>
<br>
<% @posts2.each do |post| %>
	<%= post%>
	<br>
<% end %>

<br>
<br>
<% @results.each do |post| %>
	<%= post%>
	<br>
	<br>
<% end %>