config/routes.rb
ResumeViewer::Application.routes.draw do

  get "sessions/new"

  get "home/index_temp"

  resources :users do
     resources :resumes do
        resources :sections do
          resources :items
        end
     end
  end

  resources :recruiters
  
  resources :companies do
    resources :positions
  end

  resources :sessions
  
  resources :employments
  resources :applications

  root :to => 'home#index_temp'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recruiter_log_in" => "sessions#new_recruiter", :as => "recruiter_log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "recruiter_sign_up" => "recruiters#new", :as => "recruiter_sign_up"

  get "test_site" => 'home#index', :as => "test_site"
  
  match 'uploads' => 'resumes#upload', :as => 'resume_upload'

  match "/recruiters/approve/:employment_id" => "recruiters#approve", :as =>"recruiter_approve_employment", :via => :put

end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
  
   has_many :employments
   has_many :companies, :through => :employments 
    def push_with_attributes(company, join_attrs)
      Employments.with_scope(:create => join_attrs) { self << company}
    end
  
   attr_accessible :username, :email, :password, :password_confirmation, :company

   attr_accessor :password
   before_save :encrypt_password

   validates_confirmation_of :password, :message => 'and Password confirmation do not match'
   validates_presence_of :password, :on => :create
   validates_presence_of :username
   validates_presence_of :email
   validates_uniqueness_of :email
   validates_format_of :email,
                      :with => /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}/i,
                      :message => "must be a valid address"
   validates_uniqueness_of :username

   def self.authenticate(username, password)
      user = find_by_username(username)
      if user && user.passwordHash == BCrypt::Engine.hash_secret(password, user.passwordSalt)
         user
      else
         nil
      end
   end
   
   def encrypt_password
      if password.present?
         self.passwordSalt = BCrypt::Engine.generate_salt
         self.passwordHash = BCrypt::Engine.hash_secret(password, passwordSalt)
      end
   end
  
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_filter :authorize, :only => [:edit, :update, :show, :approve]
  # GET /recruiters
  # GET /recruiters.json
  def index
    @recruiters = Recruiter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recruiters }
    end
  end

  # GET /recruiters/1
  # GET /recruiters/1.json
  def show
    @recruiter = Recruiter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recruiter }
    end
  end

  # GET /recruiters/new
  # GET /recruiters/new.json
  def new
    @recruiter = Recruiter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recruiter }
    end
  end

  # GET /recruiters/1/edit
  def edit
    @recruiter = Recruiter.find(params[:id])
  end

  # POST /recruiters
  # POST /recruiters.json
  def create
    @recruiter = Recruiter.new(params[:recruiter])

    respond_to do |format|
      if @recruiter.save
        user_session.loginRecruiter(@recruiter.id)
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully created.' }
        format.json { render json: @recruiter, status: :created, location: @recruiter }
      else
        format.html { render action: "new" }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recruiters/1
  # PUT /recruiters/1.json
  def update
    @recruiter = Recruiter.find(params[:id])

    respond_to do |format|
      if @recruiter.update_attributes(params[:recruiter])
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruiters/1
  # DELETE /recruiters/1.json
  def destroy
    @recruiter = Recruiter.find(params[:id])
    @recruiter.destroy

    respond_to do |format|
      format.html { redirect_to recruiters_url }
      format.json { head :ok }
    end
  end
  
  def approve
    @employment=Employment.find(params[:employment_id])
      if @employment.approvedByBoth
        flash[:notice] = "Association approved."
        redirect_to @employment.recruiter
      else
        flash[:notice] = "Association approval failed to go through."
        redirect_to @employment.recruiter
      end
    
  end
  
  private
  
  def authorize
    unless user_session.right_recruiter?(params[:id].to_i)
      @recruiter = Recruiter.find(params[:id])
      flash[:notice] = "That's not your page!"
      redirect_to root_path
    end
  end
  
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/_form.html.erb
<%= form_for(@recruiter) do |f| %>
  <% if @recruiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recruiter.errors.count, "error") %> prohibited this recruiter from being saved:</h2>

      <ul>
      <% @recruiter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recruiters/edit.html.erb
<h1>Edit Your Recruiter Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @recruiter %>

app/views/recruiters/index.html.erb
<h1>Listing recruiters</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recruiters.each do |recruiter| %>
  <tr>
    <td><%= recruiter.username %></td>
    <td><%= recruiter.email %></td>
    <td><%= link_to 'Show', recruiter %></td>
    <td><%= link_to 'Edit', edit_recruiter_path(recruiter) %></td>
    <td><%= link_to 'Destroy', recruiter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recruiter', new_recruiter_path %>

app/views/recruiters/new.html.erb
<h1>Create a Recruiter Account</h1>

<%= render 'form' %>

app/views/recruiters/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Username:</b>
  <%= @recruiter.username %>
</p>

<p>
  <b>Email:</b>
  <%= @recruiter.email %>
</p>



<div id="company_portal">
<div id="companyPortalLabel">
Companies
</div>

  <% recruiter_companies_by_requestType = @recruiter.employments.group_by(&:requestType) %>
  <% for requestType, employments in recruiter_companies_by_requestType %>
  	<div class = "companyRelationshipLabel">
  		<%=
  		case requestType
  			when 3
  				label="My pending requests"
  			when 2
  				label="Unanswered company requests"
  		end
  		label
  		%>	
	</div>
	<div class = "companyRelationshipSection">
	<% if requestType==3 %>
		<% for employment in employments%>
			<div class="company">
				<%= Company.find(employment.company_id).name%>
				<%= button_to 'Accept Request', recruiter_approve_employment_path(employment), :method => :put %>
    			<%= button_to 'Delete', [employment], :confirm => 'Are you sure you want to delete this association?' , :controller => employments, :method => :delete %>
			</div>
		<% end %>
	<% elsif requestType==2 %>
		<% for employment in employments%>
			<div class="company">
				<%= Company.find(employment.company_id).name%>
    			<%= button_to 'Delete', [employment], :confirm => 'Are you sure you want to delete this association?' , :controller => employments, :method => :delete %>
			</div>
		<% end %>
	<% elsif requestType==1 %>
		<% for employment in employments%>
			<div class="company">
				<%= Company.find(employment.company_id).name%>
    			<%= button_to 'Delete', [employment], :confirm => 'Are you sure you want to delete this association?' , :controller => employments, :method => :delete %>
			</div>
		<% end %>
	<% end %>
	</div>
  <% end%>

<br>
<%= link_to 'Create a new company', new_company_path(:recruiter_id => @recruiter.id) %> 
</div>


<%= link_to 'Edit My Account', edit_recruiter_path(@recruiter) %> 